version: "2"
services:
  metabase:
    image: metabase/metabase:v0.32.9
    ports:
      - "3000:3000"
    volumes:
      - ./metabase-data:/metabase-data
    environment:
      MB_DB_FILE: /metabase-data/metabase.db
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase-db
      MB_DB_PORT: 5432
      MB_DB_USER: postgres
      MB_DB_PASS: metabase
      MB_DB_HOST: metabase-db
    ports:
      - "3000:3000"
    depends_on:
      - metabase-db
  metabase-db:
    image: postgres:9.6-alpine
    volumes:
      - ./metabase-db:/var/lib/postgresql/data
    environment:
        POSTGRES_DB: metabase-db
        POSTGRES_PASSWORD: metabase
  app-db:
    image: postgres:9.6-alpine
    volumes:
      - ./app-db:/var/lib/postgresql/data
